### ISSUE TITLE
param_js

### ISSUE THREAD

**Issue by gesaleh** [jether-energy/grafana-html-panel#2]
I'm having an issue param_js seems to be null when i use iframe
aren't these the param coming from grafana ? 
like range of time and height ?

**Comment by linar-jether** [comment]
When using the iframe the values of the params_js dict are appended to the url like:
`http://my.url.com/get_my_page&from=1462141152862&to=1463173275614&height=344`

**Comment by gesaleh** [comment]
thanks in my case they are not don't know if I'm  missing something 
in the url I have 'http://x.x.x.x/map?a=1&b=2'
i didn't change the value of param_js 
but i see the parameters are appended in case of GET or POST but with the iframe no

**Comment by gesaleh** [comment]
found my error it is the fact that the link was in ' '
